apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deploy-st.fullname" . }}
  labels:
    {{- include "deploy-st.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "deploy-st.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deploy-st.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.app.repository }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "deploy-st.fullname" . }}
            - secretRef:
                name: {{ include "deploy-st.fullname" . }}
          livenessProbe:
            exec:
              command:
                - php-fpm-healthcheck
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.app | nindent 12 }}
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
