apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-st-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sschonss/deploy-st.git
    targetRevision: main
    path: helm/deploy-st
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
