apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-st-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sschonss/deploy-st.git
    targetRevision: main
    path: helm/deploy-st
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
